import os
import markdown
from weasyprint import HTML
from dotenv import load_dotenv

load_dotenv()

def generate_pdf_report(markdown_content: str, run_id: str) -> tuple[str, int]:
    """Converts Markdown text to a formatted PDF using WeasyPrint."""
    
    # Convert Markdown to HTML
    # We enable extensions for tables and code blocks which LLMs frequently output
    raw_html = markdown.markdown(markdown_content, extensions=['tables', 'fenced_code'])
    
    # Build a clean, professional HTML template
    html_template = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <style>
            @page {{
                size: A4;
                margin: 2.5cm;
                @bottom-center {{
                    content: counter(page);
                    font-size: 12px;
                    color: #7f8c8d;
                }}
            }}
            body {{ 
                font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; 
                line-height: 1.6; 
                color: #333;
            }}
            h1 {{ color: #2c3e50; text-align: center; margin-bottom: 30px; }}
            h2 {{ color: #34495e; border-bottom: 2px solid #ecf0f1; padding-bottom: 5px; margin-top: 30px; }}
            h3 {{ color: #7f8c8d; }}
            p {{ margin-bottom: 15px; text-align: justify; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
            th, td {{ border: 1px solid #bdc3c7; padding: 10px; text-align: left; }}
            th {{ background-color: #ecf0f1; }}
            code {{ background-color: #f8f9fa; padding: 2px 4px; border-radius: 4px; font-family: monospace; }}
            .footer {{ text-align: center; margin-top: 50px; font-size: 12px; color: #95a5a6; }}
        </style>
    </head>
    <body>
        {raw_html}
        <div class="footer">Automated Research Report • Generated by LangGraph</div>
    </body>
    </html>
    """
    
    # Get report directory from environment or use default
    report_dir = os.getenv("REPORT_DIR", "reports")
    os.makedirs(report_dir, exist_ok=True)
    
    # Define the output path
    file_path = os.path.join(report_dir, f"{run_id}.pdf")
    
    # Generate and save the PDF, counting exact pages
    html_doc = HTML(string=html_template)
    rendered_doc = html_doc.render()
    page_count = len(rendered_doc.pages)
    rendered_doc.write_pdf(file_path)
    
    return file_path, page_count