FROM python:3.11-slim-bookworm

WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN pip install uv

RUN uv sync

COPY . .

EXPOSE 8501

CMD ["uv", "run", "streamlit", "run", "frontend/streamlit/streamlit-app.py", "--server.port=8501", "--server.address=0.0.0.0"]